[package]
name = "json2rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
toml = "0.9.5"
lazy_static = "1.4"
