langid = "kotlin"
ext = "kt"
before_struct = """
@Serializable
data class """
after_struct = ")\n\n"
before_struct_name = ""
after_struct_name = "(\n"
keyword = "data class"
left_brace_replace_by = ""
right_brace_replace_by = ""
each_attr_format = "    val $NAME: $TYPE,\n"
number = "Int"
string = "String"
boolean = "Boolean"
array = "List<$T>"
object = "$T"
null = "Nothing?"  # kotlinx.serialization ignores nulls by default
optional = "$T?"   # Kotlin nullable types
file_header = "import kotlinx.serialization.Serializable\n\n"
file_footer = ""
indent = "    "
field_separator = ""
after_last_field = "\n"