ext = "rs"
before_struct = "#[derive(Debug, serde::Serialize, serde::Deserialize)]\npub struct "
after_struct = "}\n\n"
before_struct_name = ""
after_struct_name = " {\n"
each_attr_format = "    pub $NAME: $TYPE,\n"
number = "i64"
string = "String"
boolean = "bool"
array = "Vec<$T>"
object = "$T"
null = "serde_json::Value"
optional = "Option<$T>"
file_header = "use serde_json::Value;\n\n"
file_footer = ""
indent = "    "
field_separator = ""