ext = "ts"
before_struct = "export interface "
after_struct = "\n}\n\n"
before_struct_name = ""
after_struct_name = " {\n"
left_brace_replace_by = ""
right_brace_replace_by = ""
each_attr_format = "  $NAME: $TYPE;"
number = "number"
string = "string"
boolean = "boolean"
array = "$T[]"
object = "$T"
null = "null"
optional = "$T | null"
file_header = ""
file_footer = ""
indent = "  "
field_separator = "\n"
nullable_marker = "?"
optional_marker = "?"